import type { Game } from '../types/Game';

export const mockGames: Game[] = [
    {
        id: '1',
        title: 'Elden Ring',
        description: 'An action RPG set in the Lands Between, featuring vast open world exploration and challenging combat.',
        coverImage: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg',
        releaseDate: '2022-02-25',
        rating: 9.5,
        genres: ['RPG', 'Action'],
        platforms: ['PC', 'PlayStation 5', 'Xbox Series X'],
        relevanceScore: 98,
    },
    {
        id: '2',
        title: 'Cyberpunk 2077',
        description: 'An open-world action adventure set in Night City, a megalopolis obsessed with power and body modification.',
        coverImage: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg',
        releaseDate: '2020-12-10',
        rating: 8.2,
        genres: ['RPG', 'Action', 'Adventure'],
        platforms: ['PC', 'PlayStation 5', 'Xbox Series X'],
        relevanceScore: 90,
    },
    {
        id: '3',
        title: 'Hollow Knight',
        description: 'A challenging 2D action adventure through a vast ruined kingdom of insects and heroes.',
        coverImage: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/367520/header.jpg',
        releaseDate: '2017-02-24',
        rating: 9.0,
        genres: ['Action', 'Adventure'],
        platforms: ['PC', 'Nintendo Switch'],
        relevanceScore: 88,
    },
    {
        id: '4',
        title: 'Hades',
        description: 'A rogue-like dungeon crawler where you defy the god of death as the immortal Prince of the Underworld.',
        coverImage: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1145360/header.jpg',
        releaseDate: '2020-09-17',
        rating: 9.3,
        genres: ['Action', 'RPG'],
        platforms: ['PC', 'Nintendo Switch', 'PlayStation 5'],
        relevanceScore: 95,
    },
    {
        id: '5',
        title: 'Civilization VI',
        description: 'Build an empire to stand the test of time in this turn-based strategy game.',
        coverImage: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/289070/header.jpg',
        releaseDate: '2016-10-21',
        rating: 8.7,
        genres: ['Strategy', 'Simulation'],
        platforms: ['PC', 'Nintendo Switch', 'Mobile'],
        relevanceScore: 85,
    },
    {
        id: '6',
        title: 'Resident Evil Village',
        description: 'Survive nightmarish creatures and unravel dark mysteries in a remote mountain village.',
        coverImage: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/1196590/header.jpg',
        releaseDate: '2021-05-07',
        rating: 8.8,
        genres: ['Horror', 'Action'],
        platforms: ['PC', 'PlayStation 5', 'Xbox Series X'],
        relevanceScore: 87,
    },
    {
        id: '7',
        title: 'Stardew Valley',
        description: 'Build the farm of your dreams in this relaxing open-ended farming RPG.',
        coverImage: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg',
        releaseDate: '2016-02-26',
        rating: 9.1,
        genres: ['Simulation', 'RPG'],
        platforms: ['PC', 'Nintendo Switch', 'Mobile'],
        relevanceScore: 92,
    },
    {
        id: '8',
        title: 'Portal 2',
        description: 'A mind-bending puzzle platformer that challenges you to think with portals.',
        coverImage: 'https://shared.fastly.steamstatic.com/store_item_assets/steam/apps/620/header.jpg',
        releaseDate: '2011-04-19',
        rating: 9.8,
        genres: ['Puzzle', 'Adventure'],
        platforms: ['PC'],
        relevanceScore: 96,
    },
];